baseurl = "https://giacomopoggi.com/"
title = "Giacomo Poggi"
theme = "hugo-coder-master"
languagecode = "en"
defaultcontentlanguage = "it"
paginate = 20
canonifyurls = true
pygmentsstyle = "rrt"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pluralizelisttitles = false
googleAnalytics = "UA-164287873-1"


[params]
    author = "Giacomo Poggi"
    description = "Il sito personale di Giacomo Poggi"
    keywords = "blog,sito,personale,economia,programmazione,tecnologia"
    info = "Economista ～ Fiscalista ～ Programmatore"
    avatarurl = "images/avatar.jpg"
    footercontent = ""
    dateformat = "02/01/2006"
    hideCredits = true
    hideCopyright = false
    since = 2020

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "dark"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"


[[params.social]]
    name = "Email"
    icon = "fas fa-envelope"
    weight = 1
    url = "/email/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/giacomopoggi/"
    
[[params.social]]
    name = "Podcast"
    icon = "fa fa-podcast"
    weight = 3
    url = "https://anchor.fm/giacomopoggi"


[languages]
    [languages.it]
        languagename = "Italiano"

        [languages.it.menu]
            [[languages.it.menu.main]]
            name = "Blog"
            weight = 1
            url = "blog/"

            [[languages.it.menu.main]]
            name = "Curriculum Vitae"
            weight = 2
            url = "/pdf/cv.pdf/"


    [languages.en]
        languagename = "English"
        title = "Giacomo Poggi"

        [languages.en.params]
            author = "Giacomo Poggi"
            info = "Economist ～ Fiscalist ～ Programmer"
            description = "Giacomo Poggi's personal website"
            keywords = "blog,site,personal,economy,programming,technology"
            footercontent = "Warning: by choice, blog articles are primarily written in italian language. Only a select few will get an english translation, eventually."
            dateformat = "2006-01-02"

        [languages.en.menu]
            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "blog/"

            [[languages.en.menu.main]]
            name = "Curriculum Vitae"
            weight = 2
            url = "/pdf/cv.pdf/"

        [[languages.en.params.social]]
            name = "Email"
            icon = "fas fa-envelope"
            weight = 1
            url = "email"
            
        [[languages.en.params.social]]
            name = "LinkedIn"
            icon = "fab fa-linkedin"
            weight = 2
            url = "https://www.linkedin.com/in/giacomopoggi/"

        [[languages.en.params.social]]
            name = "Podcast"
            icon = "fa fa-podcast"
            weight = 3
            url = "https://anchor.fm/giacomopoggi"
